### ISSUE TITLE
About Data Preparation

### ISSUE THREAD

**Issue by YeSho-cpp** [clovaai/PointWSSIS#3]
Hello Thanks for the great work. I have a data set of my own, processed into COCO type, I want to ask the code has a subset of the operation and make instances_train_{subset}_w.json file and instances_train2017_{subset}_s.json file processing? Not looking closely at the code.

**Comment by qjadud1994** [comment]
We did not upload the data preprocessing code. But it can be simply implemented.
For example,

```
dat_list = [dat_1, dat_2, ... dat_N]
np.random.shuffle(dat_list)
dat_10p_s = dat_list[:N//10]
dat_10p_w = dat_list[N//10:]
save_json(dat_10p_s)
save_json(dat_10p_w)
```

**Comment by 1554236825** [comment]
Thank you very much for your work, I have my own data set, I want to know how to make weak supervised annotation on it, by checking your public data set annotation is weak supervised annotation based on frame?

**Comment by qjadud1994** [comment]
Actually, our work obtained weak (=point) annotations from instance-level masks ([here](https://github.com/clovaai/PointWSSIS/blob/bd3156e3866ac9131187f50cd0ee0cd0c2513589/AdelaiDet/adet/modeling/solov2/solov2.py#L351)) since our benchmark is the COCO dataset that has instance segmentation labels.

if a dataset has only point-labeled data (such as [here](https://github.com/naver-ai/NeglectedFreeLunch)), you can directly use them.
Also, if a dataset has bounding box labels or instance segmentation labels, you can convert them to point labels (such as using the centroid point of a box or mask.)
